name : "hello world workflow"

# this is a event that will trigger the workflow when there is a push to the main or production branch  
on:
  push:
    branches: 
      - main
      - production

jobs:
  # this is the name of the job.
  hello-world:
    # it is built in event . tell which environment to run the job.
    runs-on: ubuntu-latest
    steps:
     - name: "Print Hello world"
       run: echo "Hello world"